- name: Google Java Format
  uses: axel-op/googlejavaformat-action@v2.0.0
  with:
    # Arguments for the Google Java Format executable
    args: # optional, default is --replace
    # Pattern to match files to be formatted
    files: # optional, default is **/*.java
    # Set to true to not commit the changes
    skipCommit: # optional, default is false
